### ISSUE TITLE
Status 400 for ars endpoint get in progress assets

### ISSUE THREAD

**Issue by Baeist** [NHMDenmark/DaSSCo-Integration#133]
/ars/api/v1/assets/inprogress/?onlyFailed=false or /ars/api/v1/assets/inprogress/ are  giving me 400 back.

**Comment by Grand666** [comment]
Hi Lars, 

I can't reproduce this error, I'm getting a 200 and a list:

[
    {
        "asset_guid": "test-asset-4",
        "parent_guid": null,
        "error_timestamp": null,
        "status": "METADATA_RECEIVED",
        "error_message": null,
        "share_allocation_mb": 40
    },
    {
        "asset_guid": "test-asset-2",
        "parent_guid": "test-asset-1",
        "error_timestamp": null,
        "status": "METADATA_RECEIVED",
        "error_message": null,
        "share_allocation_mb": 40
    },
    {
        "asset_guid": "test-asset-3",
        "parent_guid": "test-asset-1",
        "error_timestamp": null,
        "status": "METADATA_RECEIVED",
        "error_message": null,
        "share_allocation_mb": 40
    },
    ...
]


When calling:
https://dassco.dk/ars/api/v1/assets/inprogress/?onlyFailed=false
https://dassco.dk/ars/api/v1/assets/inprogress/
https://dassco.dk/ars/api/v1/assets/inprogress

Called through the Postman.

**Comment by Baeist** [comment]
It was an issue with the authorization on my end. It is working.
