### ISSUE TITLE
Change from slurm to computerome

### ISSUE THREAD

**Issue by Baeist** [NHMDenmark/DaSSCo-Integration#26]
Change to the use of computerome hpc.

Immediate issue is automatically connecting without being stopped by their 2factor authentication. 

Learning to use their commands. 

Implementing commands in scripts. 

Setting up environments for running pipelines according to their guidelines.

**Comment by Baeist** [comment]
Exploring other hpc options also. Currently waiting on LUMI to get up and running again. They have scheduled maintenance until early september 24.

**Comment by bhsi-snm** [comment]
plans changed, refer to comment in https://github.com/NHMDenmark/DaSSCo-Integration/issues/26
